development:
  adapter: postgresql
  database: dorian_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: dorian_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dorian_prod
  pool: 5
  timeout: 5000
